# Project: Vanilla Web Development Template
# Created on: 2026-05-30
# Author: Finn Konrad
# License: MIT
# Description: A YAML file that lints, tests and builds each push to the GitLab repository.

stages:
  - setup
  - lint
  - test
  - build

install-packages:
  stage: setup
  image: node
  script:
    - npm ci
  cache:
    paths:
      - "node_modules/"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

lint-html:
  stage: lint
  image: node
  dependencies:
    - install-packages
  script: 
    - make lint-html
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

lint-css:
  stage: lint
  image: node
  dependencies:
    - install-packages
  script: 
    - make lint-css
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

lint-js:
  stage: lint
  image: node
  dependencies:
    - install-packages
  script: 
    - make lint-js
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

test-js:
  stage: test
  image: node
  dependencies:
    - install-packages
  script: 
    - make test-js
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

build-site:
  stage: build
  script:
    - apt install exiftool
    - apt install zip
    - make build-site
  artifacts:
    paths:
      - "build/"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
