# Project: Vanilla Web Development Template
# Created on: 2026-05-30
# Author: Finn Konrad
# License: MIT
# Description: A YAML file that lints, tests and builds each push to the GitLab repository.

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

default:
  image: node:latest
  cache:
    paths:
      - "node_modules/"

stages:
  - setup
  - lint
  - test
  - build

install-packages:
  stage: setup
  script:
    - npm ci

lint-html:
  stage: lint
  needs: ["install-packages"]
  script: 
    - make lint-html

lint-css:
  stage: lint
  needs: ["install-packages"]
  script: 
    - make lint-css

lint-js:
  stage: lint
  needs: ["install-packages"]
  script: 
    - make lint-js

test-js:
  stage: test
  needs: ["install-packages"]
  script: 
    - make test-js

build-site:
  stage: build
  needs: []
  script:
    - apt-get update
    - apt-get install -y exiftool
    - apt-get install -y zip
    - make build-site
  artifacts:
    paths:
      - "build/*"
    expire_in: 15 minutes
