# Metadata
ROOT_DIR="../"
SRC_FILES=("index.html" "src/html" "src/css" "src/js/lib" "src/js/main" "src/assets")
BUNDLE_NAME="vanilla-webdev-template"

# Archive Flags
GEN_DIR="true"
GEN_TGZ="true"
GEN_ZIP="true"
