# File Header
DATE=$(date +%Y-%m-%d)
AUTHOR="Author"
LICENSE="MIT"
DESCRIPTION="Description"

# Normalise Flags
SMOOTH_SCROLLING="true"
SET_BORDER_BOX="true"
RESET_PADDING="true"
RESET_MARGIN="true"

# Template Flags
TEMPLATE_FOCUS="true"
TEMPLATE_SELECTION="true"
TEMPLATE_IMPORT="true"
TEMPLATE_MEDIA_QUERY="true"
TEMPLATE_GLOBAL_VARIABLE="true"
