# Browser Window
STYLESHEET="stylesheet.css"
SCRIPT="script.js"

# SEO
TITLE="Title" # Short and to the point
KEYWORDS="Keywords" # 2-8 Keywords
DESCRIPTION="Description" # 150-160 Characters
AUTHOR="Author"

# Open Graph
TYPE="website"
URL="http://143.93.245.165/verzeichnis/"
IMAGE="image.jpg" # 1.91:1 Image; min. 1200x630px

# Multimedia
FAVICON="favicon.svg"
