# File Header
DATE=$(date +%Y-%m-%d)
AUTHOR="Toni Fey, Finn Konrad, Tim Zingler"
LICENSE="MIT"
DESCRIPTION="Description"

# Template Flags
TEMPLATE_CLASS="true"
TEMPLATE_FETCH_API="true"
TEMPLATE_DISPATCH_EVENT="true"
TEMPLATE_EVENT_LISTENER="true"
TEMPLATE_VITEST_TEST="true"
